FROM resin/%%RESIN_ARCH%%-node:0.10.38

# create src dir
RUN mkdir -p /usr/src/app/

# set as WORKDIR
WORKDIR /usr/src/app

# Only package.json and pre-install script here for caching purposes
COPY package.json deps.sh ./

#install deps
RUN JOBS=MAX npm install --unsafe-perm --production && npm cache clean

# Copy all of files here for caching purposes
COPY . ./

# npm start will run server.js by default
CMD npm start